CI updates

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -6,6 +6,26 @@ env:
   global:
     - NODE_VERSION=stable
 
+branches:
+  only:
+    - master
+
+cache:
+  directories:
+    - $HOME/.npm
+    - node_modules
+
+before_install:
+  - |
+    set -e
+    # fail loudly when force-pushed
+    MODIFIED_FILES=$(git diff --name-only $TRAVIS_COMMIT_RANGE)
+    # waiting for native solution https://github.com/travis-ci/travis-ci/issues/6301
+    if ! echo ${MODIFIED_FILES} | grep -qvE '(\.md$)|(^docs)/'; then
+      echo "Only docs were updated, stopping build process."
+      exit
+    fi
+
 install:
   - brew tap wix/brew
   - brew install applesimutils
